### ISSUE TITLE
Hyperlinks are not working

### ISSUE THREAD

**Issue by TimeFreeze1337** [SeongGino/Nero-umu#31]
I'm assuming that they are supposed to open in a browser, if i'm mistaken then just ignore this "Issue".

I'm talking for example about these:

![Screenshot_20241206_210555](https://github.com/user-attachments/assets/f5e58bca-aff6-4c0a-9835-47fec22eac01)

They dont open up if i click them, only thing i can do to get to the specific page is to right click and copy the link:

![Screenshot_20241206_210811](https://github.com/user-attachments/assets/8e0b4f28-3084-46d2-859b-8305fd2351b7)

**Comment by SeongGino** [comment]
Oops.

Resolved in 6198a63
