### ISSUE TITLE
Envirionment variable use-cases

### ISSUE THREAD

**Issue by keenanweaver** [SeongGino/Nero-umu#33]
Love your approach to Wine prefixing. Just wanted to make a note of my own use-cases for environment variables as while I do love the idea of something [having a special button/checkbox/whatever](https://github.com/SeongGino/Nero-umu/blob/main/README.md#things-i-likely-wont-do) for a certain use, the flexibility of using environment variables can outclass GUI elements.

* Setting `PULSE_SINK` to route Pipewire audio to a certain virtual sink for capturing to OBS
* Quickly testing games with `DXVK_CONFIG=full` and `MANGOHUD=full`, bypassing the scope of the global/user config
* Limiting framerate with `DXVK_FRAME_RATE`
* Limiting CPU cores with `WINE_CPU_TOPOLOGY`
* More esoteric stuff to get games to work at all. Soldier of Fortune II: Double Helix for instance: `MESA_EXTENSION_MAX_YEAR=2003` and `__GL_ExtensionStringVersion=17700` (arguably should go upstream to umu fixes, but lots of games aren't available digitally and I don't believe that is in scope for umu yet)

I personally think there's should be a GUI option for the most common stuff a user would do, but also a custom environment variable box for everything else.

**Comment by SeongGino** [comment]
I appreciate the thought, but there's reasons why I made the decision to omit custom environment variables inside the interface itself.

I've always disliked the practice that such options should be hidden behind what are effectively obtuse cheat codes. Half of the reason I made Nero in the first place is to make these options more visible to the beginner user that doesn't even know what an "environment" is!

If an option really is that important that it needs to be requested, and it would be helpful to more people, I'd rather have it be an option to toggle/select than maintain the existing status quo.

That being said, I should point out:
 - `DXVK_FRAME_RATE` is already added as the per-shortcut *Limit FPS*
 - The legacy GL extensions bits are already under the catch-all *Limit GL Extensions* in the advanced tab.
 
I will at least consider adding the CPU topology setting per-shortcut at some point, if it is that useful. But any other variables could just be added to Nero itself - as it will be added to Umu's environment.

But yeah, TL;DR: I'm not interested in this; it contributes to a bad practice for a new generation of new Linux gamers, and we should be advocating for accessibility in GUI apps. And unlike a certain other project I have a hand in, Nero is something I made primarily for myself. So, unless it's something I am interested in adding (or perhaps given incentive to make, wink wink), I'm not going to spend much time on it.

Still, usual FOSS reminder, feel free to fork, yadda yadda.

**Comment by keenanweaver** [comment]
Then we are in agreement! I really dislike the use of variables like these (or any other user-unfriendly status quo stuff) as 'normal' for Linux gaming, it's just historically been the case that the ghosts of penguins past utilized.

Thanks for considering and I'm looking forward to see where you take Nero!
